# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'CleverPumpkins' do
# Or platform :osx, '10.7'
pod 'RestKit', '~> 0.20.0'

# Testing and Search are optional components
pod 'RestKit/Testing', '~> 0.20.0'
pod 'RestKit/Search',  '~> 0.20.0'
end

target 'CleverPumpkinsTests' do

end

